### PR TITLE
Fix behaviour with removed operation dump files #807

### LINKED ISSUE #807: Empty EE genesis sections are writing if separated operation dump file is omitted

### PR DESCRIPTION
**Pull request by boostmultifruit**
Resolves #807

Following fixed:

- EE-genesis file sections are not writing empty if some operation-dump files are omitted by user
- If `json_metadata` operation dump file omitted by user, create-genesis tool writing all accounts with empty metadata, not with `{created_at: GENESIS}` metadata.

Also now it locks operation-dump files from another processes access, what is a bit more correct.

### CODE REVIEW

File: programs/create-genesis/ee_genesis/genesis_ee_builder.cpp [hunk 1]
```diff
@@ -31,15 +31,18 @@ genesis_ee_builder::genesis_ee_builder(const genesis_info& info, const export_in
 genesis_ee_builder::~genesis_ee_builder() {
 }
 
-golos_dump_header genesis_ee_builder::read_header(bfs::ifstream& in) {
+golos_dump_header genesis_ee_builder::read_header(bfs::ifstream& in, const bfs::path& file) {
```
Comment (afalaleev) [inline programs/create-genesis/ee_genesis/genesis_ee_builder.cpp]: `golos_dump_header` is not used, when `in` is opened in this function.

Looks better, if function will return `bfs::ifstream`.

Comment (boostmultifruit) [reply programs/create-genesis/ee_genesis/genesis_ee_builder.cpp]: @afalaleev yes, can be renamed to `open_dump()` with returning `bfs::ifstream`
